### ISSUE TITLE
compass assert dump problems

### ISSUE THREAD

**Issue by daim2k5** [ongr-io/ongr-sandbox#102]
I installed ongr without vagrant and had problem to use
"php app/console assetic:dump" the error was "/usr/bin/ruby: No such file or directory -- /usr/bin/compass (LoadError)". 
The solution was for me to change the config.yml and add 
"compass:
        bin: /usr/local/bin/compass
"
I don't know if this a local problem or general but now the demo works.

**Comment by saimaz** [comment]
Seems like you are using ruby via `rvm` or `rbenv`. In this case you must change the compass path. 

Thanks for the notice, we will update quick install docs for those people who doesn't use provided vm.
