### ISSUE TITLE
Memory exception on Composer update on magento branch on vhost

### ISSUE THREAD

**Issue by TomTom101** [ongr-io/ongr-sandbox#120]
When checking out the magento branch on the vagrant host and doing a composer update, it fails w/

```
The following exception is caused by a lack of memory and not having swap configured
Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:974
```

Issue can be resolved by doing

```
$ sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024 \\
sudo /sbin/mkswap /var/swap.1 \\
sudo /sbin/swapon /var/swap.1
```

**Comment by froide** [comment]
Thanks...

**Comment by tautrimas** [comment]
Usually `sudo service elasticsearch restart` helps immediately.

**Comment by Dawlatzai** [comment]
@TomTom101 Thanks alot...

**Comment by kazgurs** [comment]
ES is a memory hog, true. Reworked the VM with ubuntu and higher memory:
https://github.com/ongr-io/testing-vm
Clone this inside your ongr-sandbox root dir. Will probably re-make it with git submodules.

**Comment by rapaelector** [comment]
thanks  [more information](https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors)
