### ISSUE TITLE
.vagrant

### ISSUE THREAD

**Issue by ddpkts** [ongr-io/ongr-sandbox#135]
move vagrant/ to .vagrant/ so everything that is related to vm will be under .vagrant/ (now when vagrant is up there are two dirs .vagrant/ and vagrant/

**Comment by kazgurs** [comment]
Why exactly is this a necessity?

**Comment by ddpkts** [comment]
convenience

**Comment by kazgurs** [comment]
Each use creates their .vagrant dir on `vagrant up` and so committing this directory to git should never be good practice. Plus, .vagrant just contains parameters of the machine that was created. The user should very rarely have the need to access this directory. If anything it would be only more inconvenient to `cd .vagrant/vagrant` to access the manifests. Correct me if I'm wrong here.

**Comment by ddpkts** [comment]
@kazgurs kada nors prie progos papasakosiu ką turėjau galvoje

**Comment by saimaz** [comment]
:)

**Comment by saimaz** [comment]
Sometimes convience != productivity. There are plenty of users who doesn't know that has some hidden fodlers, and after moving project those folders are lost. And then, claims, claims, claims that nothing works. Sorry we will never change `vagrant` to `.vagrant`. Thank you for your support ;).
