### ISSUE TITLE
file store/magento.sh missing

### ISSUE THREAD

**Issue by RalfEggert** [ongr-io/ongr-sandbox#142]
Tried to install ONGR with Magento connector. When I reached step 6 I am not able to locate the `store/` path nor the `magento.sh` file. Did I miss something or is the step by step guide missing something?

https://ongr.readthedocs.org/en/latest/components/MagentoConnectorBundle/

Here is the step:

```
cd store
./magento.sh
```

**Comment by kazgurs** [comment]
The bundle is deprecated and no longer used.

**Comment by RalfEggert** [comment]
So, how to install Magento with ONGR?
