### ISSUE TITLE
Errors on executing Puppet manifest

### ISSUE THREAD

**Issue by jeronimo** [ongr-io/ongr-sandbox#16]
==> default: Debug: Executing '/usr/bin/apt-get update'
==> default: Error: Execution of '/usr/bin/apt-key adv --keyserver hkp://keys.gnupg.net:80 --recv-keys 89DF5277' returned 2: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.C98EqauTtz --trustdb-name /etc/apt//trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-wheezy-stable.gpg --keyring /etc/apt/trusted.gpg.d//puppetlabs-keyring.gpg --keyserver hkp://keys.gnupg.net:80 --recv-keys 89DF5277
==> default: gpg: requesting key 89DF5277 from hkp server keys.gnupg.net
==> default: gpgkeys: key 89DF5277 not found on keyserver
==> default: gpg: no valid OpenPGP data found.
==> default: gpg: Total number processed: 0
==> default: 
==> default: Error: /Stage[main]/Main/Apt::Source[packages.dotdeb.org-php55]/Apt::Key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55]/Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55]/ensure: change from absent to present failed: Execution of '/usr/bin/apt-key adv --keyserver hkp://keys.gnupg.net:80 --recv-keys 89DF5277' returned 2: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.C98EqauTtz --trustdb-name /etc/apt//trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-wheezy-stable.gpg --keyring /etc/apt/trusted.gpg.d//puppetlabs-keyring.gpg --keyserver hkp://keys.gnupg.net:80 --recv-keys 89DF5277
==> default: gpg: requesting key 89DF5277 from hkp server keys.gnupg.net
==> default: gpgkeys: key 89DF5277 not found on keyserver
==> default: gpg: no valid OpenPGP data found.
==> default: gpg: Total number processed: 0
==> default: 
==> default: Warning: /Stage[main]/Main/Apt::Source[packages.dotdeb.org-php55]/Apt::Key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55]/Anchor[apt_key 89DF5277 present]: Skipping because of failed dependencies
==> default: Warning: /Stage[main]/Main/Apt::Source[packages.dotdeb.org-php55]/File[packages.dotdeb.org-php55.list]: Skipping because of failed dependencies
==> default: Warning: /Stage[main]/Main/Apt::Source[packages.dotdeb.org-php55]/Exec[Required packages: 'debian-keyring debian-archive-keyring' for packages.dotdeb.org-php55]: Skipping because of failed dependencies
==> default: Warning: /Stage[main]/Apt::Update/Exec[apt_update]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]: Triggered 'refresh' from 1 events
==> default: Debug: /Stage[main]/Apt::Update/Exec[apt_update]: The container Class[Apt::Update] will propagate my refresh event
==> default: Debug: Class[Apt::Update]: The container Stage[main] will propagate my refresh event
==> default: Notice: /Stage[main]/Apt/Anchor[apt::update]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Apt/Anchor[apt::update]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Php/Package[php]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Php/Package[php]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Php/File[php.conf]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Php/File[php.conf]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Php::Module[mysql]/Package[PhpModule_mysql]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/Php::Module[mysql]/Package[PhpModule_mysql]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Php::Module[mcrypt]/Package[PhpModule_mcrypt]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/Php::Module[mcrypt]/Package[PhpModule_mcrypt]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Php::Module[gd]/Package[PhpModule_gd]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/Php::Module[gd]/Package[PhpModule_gd]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Php::Module[intl]/Package[PhpModule_intl]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/Php::Module[intl]/Package[PhpModule_intl]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Php::Module[cli]/Package[PhpModule_cli]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/Php::Module[cli]/Package[PhpModule_cli]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Apt::Source[packages.dotdeb.org-php55]/Anchor[apt::source::packages.dotdeb.org-php55]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/Apt::Source[packages.dotdeb.org-php55]/Anchor[apt::source::packages.dotdeb.org-php55]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Exec[php-fpm-group-fix]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/Exec[php-fpm-group-fix]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Augeas[custom]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/Augeas[custom]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/File[/etc/php5/fpm/conf.d/custom.ini]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/File[/etc/php5/fpm/conf.d/custom.ini]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/File[/etc/php5/cli/conf.d/custom.ini]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/File[/etc/php5/cli/conf.d/custom.ini]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Exec[php-fpm-owner-fix]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/Exec[php-fpm-owner-fix]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Service[php5-fpm]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/Service[php5-fpm]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Nginx::Package::Debian/Apt::Source[nginx]/Anchor[apt::source::nginx]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Nginx::Package::Debian/Apt::Source[nginx]/Anchor[apt::source::nginx]: Skipping because of failed dependencies
==> default: Debug: Apt::Source[nginx]: The container Class[Nginx::Package::Debian] will propagate my refresh event
==> default: Info: Apt::Source[nginx]: Scheduling refresh of Exec[apt_get_update_for_nginx]
==> default: Notice: /Stage[main]/Nginx::Package::Debian/Exec[apt_get_update_for_nginx]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Nginx::Package::Debian/Exec[apt_get_update_for_nginx]: Skipping because of failed dependencies
==> default: Debug: Exec[apt_get_update_for_nginx](provider=posix): Executing '/usr/bin/apt-get update'
==> default: Debug: Executing '/usr/bin/apt-get update'
==> default: Notice: /Stage[main]/Nginx::Package::Debian/Exec[apt_get_update_for_nginx]: Triggered 'refresh' from 1 events
==> default: Debug: /Stage[main]/Nginx::Package::Debian/Exec[apt_get_update_for_nginx]: The container Class[Nginx::Package::Debian] will propagate my refresh event
==> default: Notice: /Stage[main]/Main/Php::Module[xdebug]/Package[PhpModule_xdebug]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Notice: /Stage[main]/Nginx::Package::Debian/Anchor[nginx::apt_repo]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Notice: /Stage[main]/Nginx::Package::Debian/Package[nginx]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/Php::Module[xdebug]/Package[PhpModule_xdebug]: Skipping because of failed dependencies
==> default: Warning: /Stage[main]/Nginx::Package::Debian/Anchor[nginx::apt_repo]: Skipping because of failed dependencies
==> default: Warning: /Stage[main]/Nginx::Package::Debian/Package[nginx]: Skipping because of failed dependencies
==> default: Debug: Class[Nginx::Package::Debian]: The container Stage[main] will propagate my refresh event
==> default: Notice: /Stage[main]/Nginx::Package/Anchor[nginx::package::end]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Nginx::Package/Anchor[nginx::package::end]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Nginx::Config/File[/tmp/nginx.d]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Nginx::Config/File[/tmp/nginx.d]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Nginx::Config/File[/var/nginx]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Nginx::Config/File[/var/nginx]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Nginx::Config/File[/var/nginx/client_body_temp]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Nginx::Config/File[/var/nginx/client_body_temp]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Nginx::Config/File[/tmp/nginx.mail.d]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Nginx::Config/File[/tmp/nginx.mail.d]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Php::Module[curl]/Package[PhpModule_curl]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/Php::Module[curl]/Package[PhpModule_curl]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Exec[node_sources]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/Exec[node_sources]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Package[nodejs]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/Package[nodejs]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Package[npm]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/Package[npm]: Skipping because of failed dependencies
==> default: Debug: Prefetching npm resources for package
==> default: Debug: Executing ' list --json --global'
==> default: Debug: Warning: npm list --json exited with code 1
==> default: Debug: Error: npm list --json command error source did not contain any PSON!
==> default: Notice: /Stage[main]/Main/Package[phantomjs]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Notice: /Stage[main]/Nginx::Config/File[/var/nginx/proxy_temp]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Notice: /Stage[main]/Main/Php::Module[common]/Package[PhpModule_common]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Notice: /Stage[main]/Nginx::Config/File[/etc/nginx]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Notice: /Stage[main]/Nginx::Config/File[/etc/nginx/nginx.conf]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Notice: /Stage[main]/Nginx::Config/File[/etc/nginx/conf.mail.d]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/Package[phantomjs]: Skipping because of failed dependencies
==> default: Warning: /Stage[main]/Nginx::Config/File[/var/nginx/proxy_temp]: Skipping because of failed dependencies
==> default: Warning: /Stage[main]/Main/Php::Module[common]/Package[PhpModule_common]: Skipping because of failed dependencies
==> default: Warning: /Stage[main]/Nginx::Config/File[/etc/nginx]: Skipping because of failed dependencies
==> default: Warning: /Stage[main]/Nginx::Config/File[/etc/nginx/nginx.conf]: Skipping because of failed dependencies
==> default: Warning: /Stage[main]/Nginx::Config/File[/etc/nginx/conf.mail.d]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Nginx::Config/File[/etc/nginx/conf.mail.d/vhost_autogen.conf]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Nginx::Config/File[/etc/nginx/conf.mail.d/vhost_autogen.conf]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Nginx::Config/File[/etc/nginx/sites-enabled]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Nginx::Config/File[/etc/nginx/sites-enabled]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Nginx::Config/File[/etc/nginx/sites-enabled/default]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Nginx::Config/File[/etc/nginx/sites-enabled/default]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Nginx::Config/File[/etc/nginx/sites-available]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Nginx::Config/File[/etc/nginx/sites-available]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Nginx::Resource::Vhost[ongr.dev]/Concat[/etc/nginx/sites-available/ongr.dev.conf]/File[/etc/nginx/sites-available/ongr.dev.conf]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/Nginx::Resource::Vhost[ongr.dev]/Concat[/etc/nginx/sites-available/ongr.dev.conf]/File[/etc/nginx/sites-available/ongr.dev.conf]: Skipping because of failed dependencies
==> default: Info: Concat[/etc/nginx/sites-available/ongr.dev.conf]: Scheduling refresh of Class[Nginx::Service]
==> default: Debug: Concat[/etc/nginx/sites-available/ongr.dev.conf]: The container Nginx::Resource::Vhost[ongr.dev] will propagate my refresh event
==> default: Notice: /Stage[main]/Main/Nginx::Resource::Vhost[ongr.dev]/File[ongr.dev.conf symlink]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Main/Nginx::Resource::Vhost[ongr.dev]/File[ongr.dev.conf symlink]: Skipping because of failed dependencies
==> default: Debug: Nginx::Resource::Vhost[ongr.dev]: The container Class[Main] will propagate my refresh event
==> default: Debug: Class[Main]: The container Stage[main] will propagate my refresh event
==> default: Notice: /Stage[main]/Nginx::Config/File[/etc/nginx/conf.d]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Nginx::Config/File[/etc/nginx/conf.d]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Nginx::Config/File[/etc/nginx/conf.d/proxy.conf]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Nginx::Config/File[/etc/nginx/conf.d/proxy.conf]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Nginx::Config/File[/etc/nginx/conf.d/example_ssl.conf]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Nginx::Config/File[/etc/nginx/conf.d/example_ssl.conf]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Nginx::Config/File[/etc/nginx/conf.d/vhost_autogen.conf]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Nginx::Config/File[/etc/nginx/conf.d/vhost_autogen.conf]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Nginx::Config/File[/etc/nginx/conf.d/default.conf]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Nginx::Config/File[/etc/nginx/conf.d/default.conf]: Skipping because of failed dependencies
==> default: Info: Class[Nginx::Service]: Scheduling refresh of Service[nginx]
==> default: Notice: /Stage[main]/Nginx::Service/Service[nginx]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Nginx::Service/Service[nginx]: Skipping because of failed dependencies
==> default: Debug: Service[nginx](provider=debian): Could not find nginx in /etc/init.d
==> default: Debug: Service[nginx](provider=debian): Could not find nginx.sh in /etc/init.d
==> default: Error: /Stage[main]/Nginx::Service/Service[nginx]: Failed to call refresh: Could not find init script for 'nginx'
==> default: Error: /Stage[main]/Nginx::Service/Service[nginx]: Could not find init script for 'nginx'
==> default: Notice: /Stage[main]/Nginx/Anchor[nginx::end]: Dependency Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php55] has failures: true
==> default: Warning: /Stage[main]/Nginx/Anchor[nginx::end]: Skipping because of failed dependencies

**Comment by gyKa** [comment]
I had the same problem, a solution of @Zylius was correct.

**Comment by saimaz** [comment]
The #38 should solve this issue. @jeronimo can you check if it's working for you?

**Comment by saimaz** [comment]
Looks like this issue is solved. Closing, if it will repeat please reopen it.
