### ISSUE TITLE
Move contents from wiki to demo bundles docs

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ongr-sandbox#18]
Make sure to change format to rst.

**Comment by tautrimas** [comment]
@saimaz, can you organise removal of links to wiki from http://ongr.io/? Then, wiki can be safely deleted.

**Comment by saimaz** [comment]
I'll try.

**Comment by saimaz** [comment]
Links in ongr.io are changed. Can we close it? Or is there something else here?

**Comment by chyzas** [comment]
Some of reference links doesn't work on in:
https://github.com/ongr-io/ongr-sandbox/blob/master/src/ONGR/DemoBundle/Resources/doc/index.rst
https://github.com/ongr-io/ongr-handbook/blob/master/source/handbook/contributing/contributing.rst

**Comment by tautrimas** [comment]
Github browsing has been abandoned due to the feature shortage like table of contents, etc.

**Comment by tautrimas** [comment]
Great, one link has been changed to point to readthedocs.org, but there is one still pending in http://ongr.io/es-bundle/. Let's wait till PR https://github.com/ongr-io/ElasticsearchBundle/pull/131 get's merged and the link is replaced.

**Comment by tautrimas** [comment]
Ther PR has been merged and link can be updated in http://ongr.io/es-bundle/. Should point to https://ongr.readthedocs.org/en/latest/components/ElasticsearchBundle/Resources/doc/index.html

**Comment by saimaz** [comment]
Soon it should be updated.
