### ISSUE TITLE
Category tree is not formatted after composer update

### ISSUE THREAD

**Issue by chyzas** [ongr-io/ongr-sandbox#28]
CategoryService
the first problem is with const category_root_id. Workaround is change from 'category_root_id' to 'oxrootid' at the moment. The const should be moved to config.
the second buildQuery method, it should be $search->addQuery(new TermQuery('active', true), 'must');
not 'is_active'. The property from 'is_active" changed to 'active' in CategoryTrait too.

**Comment by tautrimas** [comment]
Has this issue been resolved?

**Comment by chyzas** [comment]
Yes, this issue has been resolved by:
https://github.com/ongr-io/ContentBundle/pull/33
https://github.com/ongr-io/ContentBundle/pull/34
