### ISSUE TITLE
add mysql requirement for user group adding in vagrant manifest

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ongr-sandbox#32]

**Comment by MindaugasR** [comment]
Is it not already added?
https://github.com/ongr-io/ongr-sandbox/blob/master/vagrant/manifests/default.pp#L27

**Comment by saimaz** [comment]
No, it should look like:

```
user { "vagrant_user":
    name       => vagrant,
    ensure     => present,
    groups     => ["www-data", "mysql"],
    require     => Class['::mysql::server']
}
```

I do not understand why vagrant user needs mysql group?

**Comment by MindaugasR** [comment]
it is required for tests and mysql binlog
