### ISSUE TITLE
Method ContentService::getDataForSnippet does not exist anymore

### ISSUE THREAD

**Issue by martiis** [ongr-io/ongr-sandbox#59]
https://github.com/ongr-io/ongr-sandbox/blob/88581c492cd1614a5d81b970fbc7aab829801263/src/ONGR/DemoBundle/Controller/ContentController.php#L100

https://github.com/ongr-io/ContentBundle/blob/master/Service/ContentService.php

**Comment by tfe2012** [comment]
resolved with https://github.com/ongr-io/ongr-sandbox/commit/50ed280d3b25beecea03ecfe3f10678c504fc102
