### ISSUE TITLE
Need test for page, that doesn't exists.

### ISSUE THREAD

**Issue by gyKa** [ongr-io/ongr-sandbox#67]
This test is skipped while https://github.com/ongr-io/ElasticsearchBundle/issues/136 isn't fixed. At this moment the page e.g. "/page/doesntexists/" throws an exception and sets HTTP status code to 500. Expected behavior: 404 status code.

**Comment by gyKa** [comment]
>= v0.3.0 of ElasticseachBundle has a solution for this problem.

**Comment by AndriusBil** [comment]
ContentControllerTest praeina be problemų dabartinėje sandbox versijoje
