### ISSUE TITLE
VirtualBox instaltion errors in Quick start guide 

### ISSUE THREAD

**Issue by trylika** [ongr-io/ongr-sandbox#8]
After installing VirtualBox from https://www.virtualbox.org "vagrant up" fails.

It's better to install using apt-get according to https://www.virtualbox.org/wiki/Linux_Downloads "Debian-based Linux distributions" guide. Documentation update is needed.

**Comment by tautrimas** [comment]
Please, reopen if problem persists. Yes, we always recommend installing latest versions from vendor web pages as these technologies are evolving together.
