### ISSUE TITLE
[puppet] New MySQL puppet module needs updated config

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/ongr-sandbox#84]
Puppet module 3.1.0 doesn't like this:

https://github.com/ongr-io/ongr-sandbox/blob/5abfca4f2187170202d7626480deffc896e94546/vagrant/manifests/default.pp#L93-L108

Now, module creates the file automatically. [Proof](https://github.com/puppetlabs/puppetlabs-mysql/blob/a839489add71cbab02d728700f14cdea2a700759/manifests/server/config.pp#L24-L32).

We should remove file creation and update `'log-bin' => 'mysql-bin',` to use full path.

**Comment by saimaz** [comment]
@valdas406  is working on docker integration. It is only question of time when it will be ready. I hope we will support at least `3.5` puppet or even `3.7`.

**Comment by saimaz** [comment]
[Testing VM](https://github.com/ongr-io/testing-vm) doesn't have this issue any more.
